#!/usr/bin/python2.7
import time
import socket
from py_hosted import config, node
from py_clock import update_time, determine_now

config.restart_on_update()
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
IP_PORT = ("127.0.0.1", 4444)


while True:
    now = determine_now(config.debug_datetime)
    update_time(node, now)
    time.sleep(1)